apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2025-08-23T10:26:56Z"
  generation: 1
  labels:
    app: hello-openshift
  name: hello-openshift
  namespace: do280-ch1
  uid: bd221f94-308d-4ff8-9052-04f1bfafa381
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello-openshift
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-openshift
    spec:
      containers:
      - image: registry.access.redhat.com/redhattraining/hello-world-nginx:v1.0
        imagePullPolicy: IfNotPresent
        name: hello-world-nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
